# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yQ8WHk7zoQrbTsQPLt9DB_euSxjlSF7W
"""

graph   =   {'A':   ['B',   'C'],
'B':   ['C',   'D'],
'C':   ['D','F'],
'D':   ['C','E'],
'E': ['F'],
'F':   ['C','E']}

def find_path(graph, start, end, path=[]):
    path = path + [start]
    if start == end:
       return path
    if start not in graph:
       return None
    for node in graph[start]:
        if node not in path:
           newpath = find_path(graph, node, end, path)
           if newpath: return newpath
    return None

result = find_path(graph, 'A', 'D')
print(result)